"""
Auto-generated Flask Application

Generated by Intelligent Scaffolder v1.0
Stack: flask
Blocks: 
Entities: Task
"""

from flask import Flask

from routes.task_routes import task_bp


def create_app():
    """Application factory."""
    app = Flask(__name__)
    app.secret_key = "change-me-in-production"

    # Entity routes
    app.register_blueprint(task_bp)

    @app.route("/")
    def index():
        return {"status": "ok", "message": "API is running"}

    return app


if __name__ == "__main__":
    app = create_app()
    app.run(debug=True)