/**
 * Ultimate Demo - Generated by Blueprint Ultimate
 * Demo app built with Ultimate
 * Blocks: storage_sqlite, crud_routes, auth_basic
 */
import express from 'express';
const app = express();
app.use(express.json());

let items: any[] = [];

app.get('/', (req, res) => {
    res.send('<h1>Ultimate Demo</h1><p>TypeScript/Express backend</p>');
});

app.get('/api/items', (req, res) => {
    res.json({ items });
});

app.post('/api/items', (req, res) => {
    items.push(req.body);
    res.json({ success: true });
});

app.listen(5000, () => console.log('Server running on port 5000'));
