// Ultimate Demo - Generated by Blueprint Ultimate
// Demo app built with Ultimate
// Blocks: storage_sqlite, crud_routes, auth_basic
package main

import (
    "github.com/gin-gonic/gin"
    "net/http"
)

var items []map[string]interface{}

func main() {
    r := gin.Default()
    
    r.GET("/", func(c *gin.Context) {
        c.String(http.StatusOK, "<h1>Ultimate Demo</h1><p>Go/Gin backend</p>")
    })
    
    r.GET("/api/items", func(c *gin.Context) {
        c.JSON(http.StatusOK, gin.H{"items": items})
    })
    
    r.POST("/api/items", func(c *gin.Context) {
        var item map[string]interface{}
        c.BindJSON(&item)
        items = append(items, item)
        c.JSON(http.StatusOK, gin.H{"success": true})
    })
    
    r.Run(":5000")
}
