#!/usr/bin/env python3
"""
IDEA - Simple Idea to Working App

Your development helper. Describe what you want, get what you need.

Usage:
    python idea.py "recipe manager with search"     # Analyze an idea
    python idea.py --build recipe-manager           # Generate starter app
    python idea.py --list                           # Show available components  
    python idea.py --analyze path/to/code           # Understand existing code
"""

import sys
import os
import re
import json
import sqlite3
from pathlib import Path
from datetime import datetime

# =============================================================================
# COMPONENT LIBRARY
# =============================================================================

COMPONENTS = {
    "storage_sqlite": {
        "name": "SQLite Database",
        "desc": "Local file-based database, perfect for personal apps",
        "keywords": ["store", "save", "data", "database", "persist", "remember"],
    },
    "crud_routes": {
        "name": "CRUD API", 
        "desc": "Create, Read, Update, Delete endpoints",
        "keywords": ["add", "edit", "delete", "list", "manage", "crud"],
    },
    "search": {
        "name": "Search/Filter",
        "desc": "Find items by keyword",
        "keywords": ["search", "find", "filter", "query", "lookup"],
    },
    "web_ui": {
        "name": "Web Interface",
        "desc": "Simple HTML/CSS/JS frontend",
        "keywords": ["ui", "interface", "web", "page", "frontend", "visual"],
    },
    "auth_basic": {
        "name": "Basic Auth",
        "desc": "Simple username/password login",
        "keywords": ["login", "auth", "user", "password", "secure", "protect"],
    },
    "export": {
        "name": "Export Data",
        "desc": "Download your data as JSON/CSV",
        "keywords": ["export", "download", "backup", "csv", "json"],
    }
}

# =============================================================================
# IDEA ANALYZER
# =============================================================================

def analyze_idea(description: str) -> dict:
    """Parse a natural language idea into components."""
    desc_lower = description.lower()
    
    detected = ["storage_sqlite", "crud_routes", "web_ui"]
    reasoning = [
        "SQLite: Local storage for your data",
        "CRUD API: Add, view, edit, delete items",
        "Web UI: Browser-based interface"
    ]
    
    for comp_id, comp in COMPONENTS.items():
        if comp_id in detected:
            continue
        for keyword in comp["keywords"]:
            if keyword in desc_lower:
                detected.append(comp_id)
                reasoning.append(f"{comp['name']}: Detected '{keyword}'")
                break
    
    return {
        "description": description,
        "components": detected,
        "reasoning": reasoning,
        "slug": slugify(description)
    }

def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r'[^\w\s-]', '', text)
    text = re.sub(r'[\s_]+', '-', text)
    return text[:30].strip('-')

# =============================================================================
# APP GENERATOR
# =============================================================================

def generate_app(name: str, components: list) -> Path:
    """Generate a complete working Flask app."""
    
    output_dir = Path(__file__).parent / "output" / name
    output_dir.mkdir(parents=True, exist_ok=True)
    
    has_auth = "auth_basic" in components
    has_search = "search" in components
    has_export = "export" in components
    
    title = name.replace("-", " ").title()
    
    # Build app.py content piece by piece
    lines = []
    lines.append('#!/usr/bin/env python3')
    lines.append('"""')
    lines.append(title)
    lines.append('Generated by idea.py')
    lines.append('"""')
    lines.append('')
    lines.append('from flask import Flask, request, jsonify, redirect, session')
    lines.append('import sqlite3')
    lines.append('from pathlib import Path')
    lines.append('')
    lines.append('app = Flask(__name__)')
    lines.append(f'app.secret_key = "dev-secret-{name}"')
    lines.append('')
    lines.append('DB_PATH = Path(__file__).parent / "data.db"')
    lines.append('')
    lines.append('def get_db():')
    lines.append('    conn = sqlite3.connect(DB_PATH)')
    lines.append('    conn.row_factory = sqlite3.Row')
    lines.append('    return conn')
    lines.append('')
    lines.append('def init_db():')
    lines.append('    with get_db() as conn:')
    lines.append('        conn.execute("""')
    lines.append('            CREATE TABLE IF NOT EXISTS items (')
    lines.append('                id INTEGER PRIMARY KEY AUTOINCREMENT,')
    lines.append('                content TEXT NOT NULL,')
    lines.append('                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP')
    lines.append('            )')
    lines.append('        """)')
    lines.append('        conn.commit()')
    lines.append('')
    
    if has_auth:
        lines.append('from functools import wraps')
        lines.append('')
        lines.append('USERS = {"admin": "admin123"}')
        lines.append('')
        lines.append('def login_required(f):')
        lines.append('    @wraps(f)')
        lines.append('    def decorated(*args, **kwargs):')
        lines.append('        if "user" not in session:')
        lines.append('            return redirect("/login")')
        lines.append('        return f(*args, **kwargs)')
        lines.append('    return decorated')
        lines.append('')
        lines.append('@app.route("/login", methods=["GET", "POST"])')
        lines.append('def login():')
        lines.append('    if request.method == "POST":')
        lines.append('        if USERS.get(request.form.get("username")) == request.form.get("password"):')
        lines.append('            session["user"] = request.form.get("username")')
        lines.append('            return redirect("/")')
        lines.append('    return open(Path(__file__).parent / "templates" / "login.html").read()')
        lines.append('')
        lines.append('@app.route("/logout")')
        lines.append('def logout():')
        lines.append('    session.pop("user", None)')
        lines.append('    return redirect("/login")')
        lines.append('')
    
    lines.append('@app.route("/api/items", methods=["GET"])')
    lines.append('def list_items():')
    lines.append('    with get_db() as conn:')
    lines.append('        items = conn.execute("SELECT * FROM items ORDER BY created_at DESC").fetchall()')
    lines.append('        return jsonify({"items": [dict(row) for row in items]})')
    lines.append('')
    lines.append('@app.route("/api/items", methods=["POST"])')
    lines.append('def create_item():')
    lines.append('    data = request.get_json() or {}')
    lines.append('    content = data.get("content", "").strip()')
    lines.append('    if not content:')
    lines.append('        return jsonify({"error": "Content required"}), 400')
    lines.append('    with get_db() as conn:')
    lines.append('        cursor = conn.execute("INSERT INTO items (content) VALUES (?)", (content,))')
    lines.append('        conn.commit()')
    lines.append('        return jsonify({"id": cursor.lastrowid, "content": content})')
    lines.append('')
    lines.append('@app.route("/api/items/<int:item_id>", methods=["DELETE"])')
    lines.append('def delete_item(item_id):')
    lines.append('    with get_db() as conn:')
    lines.append('        conn.execute("DELETE FROM items WHERE id = ?", (item_id,))')
    lines.append('        conn.commit()')
    lines.append('        return jsonify({"deleted": item_id})')
    lines.append('')
    
    if has_search:
        lines.append('@app.route("/api/search")')
        lines.append('def search_items():')
        lines.append('    q = request.args.get("q", "")')
        lines.append('    with get_db() as conn:')
        lines.append('        items = conn.execute(')
        lines.append('            "SELECT * FROM items WHERE content LIKE ?",')
        lines.append('            (f"%{q}%",)')
        lines.append('        ).fetchall()')
        lines.append('        return jsonify({"items": [dict(row) for row in items]})')
        lines.append('')
    
    if has_export:
        lines.append('@app.route("/api/export")')
        lines.append('def export_items():')
        lines.append('    with get_db() as conn:')
        lines.append('        items = conn.execute("SELECT * FROM items").fetchall()')
        lines.append('    return jsonify([dict(row) for row in items])')
        lines.append('')
    
    lines.append('@app.route("/")')
    if has_auth:
        lines.append('@login_required')
    lines.append('def index():')
    lines.append('    return open(Path(__file__).parent / "templates" / "index.html").read()')
    lines.append('')
    lines.append('if __name__ == "__main__":')
    lines.append('    init_db()')
    lines.append('    print()')
    lines.append('    print("=" * 50)')
    lines.append(f'    print("  {title}")')
    lines.append('    print("=" * 50)')
    lines.append('    print()')
    lines.append('    print("  http://localhost:5000")')
    if has_auth:
        lines.append('    print()')
        lines.append('    print("  Login: admin / admin123")')
    lines.append('    print()')
    lines.append('    app.run(debug=True, port=5000)')
    
    app_py = '\n'.join(lines)
    (output_dir / "app.py").write_text(app_py)
    
    # Create templates directory
    templates_dir = output_dir / "templates"
    templates_dir.mkdir(exist_ok=True)
    
    # Write index.html
    index_html = build_index_html(title, has_auth, has_search, has_export)
    (templates_dir / "index.html").write_text(index_html)
    
    # Write login.html if auth enabled
    if has_auth:
        login_html = build_login_html()
        (templates_dir / "login.html").write_text(login_html)
    
    # Write README
    readme_lines = [f'# {title}', '', '## Run', '', '```bash', f'cd {output_dir}', 'python app.py', '```', '', 'Open http://localhost:5000']
    if has_auth:
        readme_lines.extend(['', '## Login', '', 'Default: admin / admin123'])
    (output_dir / "README.md").write_text('\n'.join(readme_lines))
    
    return output_dir


def build_index_html(title, has_auth, has_search, has_export):
    """Build the index.html template."""
    
    search_html = ''
    if has_search:
        search_html = '''
        <div style="margin-bottom:20px">
            <input type="text" id="searchInput" placeholder="Search..." 
                   oninput="searchItems()" style="width:100%;padding:12px;
                   background:#1a1a2e;border:2px solid #333;border-radius:8px;color:white">
        </div>'''
    
    export_html = ''
    if has_export:
        export_html = '''
        <div style="margin-top:20px">
            <a href="/api/export" download="data.json">
                <button style="background:#333;padding:10px 20px;color:white;border:none;border-radius:6px;cursor:pointer">
                    Export JSON
                </button>
            </a>
        </div>'''
    
    logout_html = ''
    if has_auth:
        logout_html = '''<a href="/logout"><button style="background:#333;padding:8px 16px;
                      color:white;border:none;border-radius:6px;cursor:pointer">Logout</button></a>'''
    
    search_js = ''
    if has_search:
        search_js = '''
        async function searchItems() {
            const q = document.getElementById('searchInput').value;
            const resp = await fetch('/api/search?q=' + encodeURIComponent(q));
            const data = await resp.json();
            renderItems(data.items);
        }'''
    
    return f'''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: -apple-system, sans-serif; background: #0f0f1a; color: #e0e0e0; min-height: 100vh; }}
        .container {{ max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #667eea; margin-bottom: 20px; }}
        .header {{ display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px; }}
        .toolbar {{ display: flex; gap: 10px; margin-bottom: 20px; }}
        input[type="text"] {{ flex: 1; padding: 12px; background: #1a1a2e; border: 2px solid #333; 
                             border-radius: 8px; color: white; font-size: 16px; }}
        input:focus {{ outline: none; border-color: #667eea; }}
        button {{ padding: 12px 24px; background: #667eea; color: white; border: none; 
                 border-radius: 8px; cursor: pointer; font-weight: 600; }}
        button:hover {{ background: #5a6fd6; }}
        .items {{ display: flex; flex-direction: column; gap: 10px; }}
        .item {{ background: #1a1a2e; padding: 15px; border-radius: 8px; 
                display: flex; justify-content: space-between; align-items: center; }}
        .empty {{ text-align: center; padding: 40px; color: #666; }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{title}</h1>
            {logout_html}
        </div>
        {search_html}
        <div class="toolbar">
            <input type="text" id="newItem" placeholder="Add new item..." 
                   onkeypress="if(event.key==='Enter')addItem()">
            <button onclick="addItem()">Add</button>
        </div>
        
        <div class="items" id="itemList">
            <div class="empty">Loading...</div>
        </div>
        {export_html}
    </div>
    
    <script>
        async function loadItems() {{
            const resp = await fetch('/api/items');
            const data = await resp.json();
            renderItems(data.items);
        }}
        
        function renderItems(items) {{
            const container = document.getElementById('itemList');
            if (items.length === 0) {{
                container.innerHTML = '<div class="empty">No items yet</div>';
                return;
            }}
            container.innerHTML = items.map(item => 
                '<div class="item"><span>' + item.content + '</span>' +
                '<button onclick="deleteItem(' + item.id + ')" style="background:#e74c3c;padding:6px 12px;font-size:12px">Delete</button></div>'
            ).join('');
        }}
        
        async function addItem() {{
            const input = document.getElementById('newItem');
            const content = input.value.trim();
            if (!content) return;
            await fetch('/api/items', {{
                method: 'POST',
                headers: {{'Content-Type': 'application/json'}},
                body: JSON.stringify({{content}})
            }});
            input.value = '';
            loadItems();
        }}
        
        async function deleteItem(id) {{
            await fetch('/api/items/' + id, {{method: 'DELETE'}});
            loadItems();
        }}
        {search_js}
        loadItems();
    </script>
</body>
</html>'''


def build_login_html():
    """Build the login.html template."""
    return '''<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <style>
        body { font-family: sans-serif; background: #1a1a2e; display: flex; 
               justify-content: center; align-items: center; min-height: 100vh; margin: 0; }
        .box { background: #16213e; padding: 40px; border-radius: 12px; width: 300px; }
        h2 { color: white; margin-bottom: 20px; }
        input { width: 100%; padding: 12px; margin-bottom: 12px; border: none; 
                border-radius: 6px; box-sizing: border-box; }
        button { width: 100%; padding: 12px; background: #667eea; color: white; 
                 border: none; border-radius: 6px; cursor: pointer; }
        .hint { background: rgba(102,126,234,0.2); padding: 10px; border-radius: 6px; 
                margin-bottom: 15px; color: #a0a0ff; font-size: 12px; text-align: center; }
    </style>
</head>
<body>
    <div class="box">
        <h2>Login</h2>
        <div class="hint">Default: admin / admin123</div>
        <form method="POST">
            <input name="username" placeholder="Username" required>
            <input name="password" type="password" placeholder="Password" required>
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>'''


# =============================================================================
# CODE ANALYZER
# =============================================================================

def analyze_code(path: str) -> dict:
    """Analyze existing code to understand its architecture."""
    path = Path(path)
    if not path.exists():
        return {"error": f"Path not found: {path}"}
    
    patterns = {
        "Flask": [r"from flask import", r"Flask\(__name__\)"],
        "FastAPI": [r"from fastapi import"],
        "SQLite": [r"sqlite3", r"\.db"],
        "PostgreSQL": [r"psycopg2", r"postgresql://"],
        "Auth": [r"login", r"session\[", r"@login_required"],
        "REST API": [r"@app\.route"],
    }
    
    detected = {}
    files = [path] if path.is_file() else list(path.rglob("*.py"))
    
    for file in files:
        try:
            content = file.read_text(errors='ignore')
            for tech, regexes in patterns.items():
                for regex in regexes:
                    if re.search(regex, content, re.IGNORECASE):
                        detected.setdefault(tech, []).append(file.name)
                        break
        except:
            pass
    
    return {
        "path": str(path),
        "files": len(files),
        "detected": {k: list(set(v))[:3] for k, v in detected.items()}
    }

# =============================================================================
# CLI
# =============================================================================

def main():
    args = sys.argv[1:]
    
    if not args:
        print("""
IDEA - Your Development Helper

Usage:
  python idea.py "your app idea"     Analyze and get recommendations
  python idea.py --build name        Generate a working app
  python idea.py --list              Show available components
  python idea.py --analyze path      Understand existing code

Examples:
  python idea.py "recipe manager with search"
  python idea.py --build recipe-manager --search
  python idea.py --analyze ./my-project
""")
        return
    
    if args[0] == "--list":
        print("\nAVAILABLE COMPONENTS")
        print("=" * 40)
        for cid, c in COMPONENTS.items():
            print(f"\n{c['name']}")
            print(f"  {c['desc']}")
        print()
        return
    
    if args[0] == "--analyze" and len(args) > 1:
        result = analyze_code(args[1])
        print(f"\nAnalyzing: {result['path']}")
        print(f"Files: {result.get('files', 0)}")
        print("\nDetected:")
        for tech, files in result.get('detected', {}).items():
            print(f"  - {tech}")
        print()
        return
    
    if args[0] == "--build" and len(args) > 1:
        name = args[1]
        components = ["storage_sqlite", "crud_routes", "web_ui"]
        if "--auth" in args:
            components.append("auth_basic")
        if "--search" in args:
            components.append("search")
        if "--export" in args:
            components.append("export")
        
        output_dir = generate_app(name, components)
        print(f"\nCreated: {output_dir}")
        print(f"\nRun it:")
        print(f"  cd {output_dir}")
        print(f"  python app.py")
        print()
        return
    
    # Default: analyze idea
    idea = " ".join(args)
    result = analyze_idea(idea)
    
    print(f'\nIDEA: "{idea}"')
    print("\nYOU'LL NEED:")
    for r in result["reasoning"]:
        print(f"  - {r}")
    
    extras = []
    if "auth_basic" in result["components"]:
        extras.append("--auth")
    if "search" in result["components"]:
        extras.append("--search")
    if "export" in result["components"]:
        extras.append("--export")
    
    cmd = f'python idea.py --build "{result["slug"]}"'
    if extras:
        cmd += " " + " ".join(extras)
    
    print(f"\nGENERATE:")
    print(f"  {cmd}")
    print()

if __name__ == "__main__":
    main()
