"""
Complete Todo App - Generated by Blueprint Scaffolder

Run with: python app.py
Open: http://localhost:5000
"""

from flask import Flask, request, jsonify, render_template_string
from flask_cors import CORS
from datetime import datetime
import json
import os

app = Flask(__name__)
CORS(app)
app.secret_key = os.environ.get("SECRET_KEY", "dev-secret-change-in-prod")

# =============================================================================
# STORAGE (JSON file-based for simplicity)
# =============================================================================

DATA_FILE = "data/tasks.json"

def ensure_data_dir():
    os.makedirs("data", exist_ok=True)
    if not os.path.exists(DATA_FILE):
        with open(DATA_FILE, "w") as f:
            json.dump([], f)

def load_tasks():
    ensure_data_dir()
    with open(DATA_FILE, "r") as f:
        return json.load(f)

def save_tasks(tasks):
    ensure_data_dir()
    with open(DATA_FILE, "w") as f:
        json.dump(tasks, f, indent=2, default=str)

def get_next_id():
    tasks = load_tasks()
    if not tasks:
        return 1
    return max(t["id"] for t in tasks) + 1

# =============================================================================
# API ROUTES
# =============================================================================

@app.route("/api/tasks", methods=["GET"])
def list_tasks():
    """List all tasks."""
    tasks = load_tasks()
    return jsonify({"tasks": tasks, "total": len(tasks)})

@app.route("/api/tasks", methods=["POST"])
def create_task():
    """Create a new task."""
    data = request.get_json()
    
    if not data or not data.get("title"):
        return jsonify({"error": "Title is required"}), 400
    
    task = {
        "id": get_next_id(),
        "title": data["title"],
        "description": data.get("description", ""),
        "done": False,
        "priority": data.get("priority", "medium"),
        "created_at": datetime.now().isoformat(),
        "updated_at": datetime.now().isoformat(),
    }
    
    tasks = load_tasks()
    tasks.append(task)
    save_tasks(tasks)
    
    return jsonify(task), 201

@app.route("/api/tasks/<int:task_id>", methods=["GET"])
def get_task(task_id):
    """Get a single task."""
    tasks = load_tasks()
    task = next((t for t in tasks if t["id"] == task_id), None)
    
    if not task:
        return jsonify({"error": "Task not found"}), 404
    
    return jsonify(task)

@app.route("/api/tasks/<int:task_id>", methods=["PUT"])
def update_task(task_id):
    """Update a task."""
    data = request.get_json()
    tasks = load_tasks()
    
    for i, task in enumerate(tasks):
        if task["id"] == task_id:
            task.update({
                "title": data.get("title", task["title"]),
                "description": data.get("description", task["description"]),
                "done": data.get("done", task["done"]),
                "priority": data.get("priority", task["priority"]),
                "updated_at": datetime.now().isoformat(),
            })
            save_tasks(tasks)
            return jsonify(task)
    
    return jsonify({"error": "Task not found"}), 404

@app.route("/api/tasks/<int:task_id>", methods=["DELETE"])
def delete_task(task_id):
    """Delete a task."""
    tasks = load_tasks()
    original_len = len(tasks)
    tasks = [t for t in tasks if t["id"] != task_id]
    
    if len(tasks) == original_len:
        return jsonify({"error": "Task not found"}), 404
    
    save_tasks(tasks)
    return "", 204

@app.route("/api/tasks/<int:task_id>/toggle", methods=["POST"])
def toggle_task(task_id):
    """Toggle task completion."""
    tasks = load_tasks()
    
    for task in tasks:
        if task["id"] == task_id:
            task["done"] = not task["done"]
            task["updated_at"] = datetime.now().isoformat()
            save_tasks(tasks)
            return jsonify(task)
    
    return jsonify({"error": "Task not found"}), 404

# =============================================================================
# HTML FRONTEND
# =============================================================================

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo App - Blueprint Demo</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 2rem;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
        }
        h1 {
            color: white;
            text-align: center;
            margin-bottom: 2rem;
            font-size: 2.5rem;
        }
        .subtitle {
            color: rgba(255,255,255,0.8);
            text-align: center;
            margin-bottom: 2rem;
            font-size: 0.9rem;
        }
        .card {
            background: white;
            border-radius: 16px;
            padding: 2rem;
            box-shadow: 0 20px 60px rgba(0,0,0,0.2);
        }
        .add-form {
            display: flex;
            gap: 0.5rem;
            margin-bottom: 1.5rem;
        }
        .add-form input {
            flex: 1;
            padding: 0.75rem 1rem;
            border: 2px solid #e0e0e0;
            border-radius: 8px;
            font-size: 1rem;
            transition: border-color 0.2s;
        }
        .add-form input:focus {
            outline: none;
            border-color: #667eea;
        }
        .add-form button {
            padding: 0.75rem 1.5rem;
            background: #667eea;
            color: white;
            border: none;
            border-radius: 8px;
            font-size: 1rem;
            cursor: pointer;
            transition: background 0.2s;
        }
        .add-form button:hover { background: #5a6fd6; }
        .task-list {
            list-style: none;
        }
        .task-item {
            display: flex;
            align-items: center;
            padding: 1rem;
            border-bottom: 1px solid #f0f0f0;
            transition: background 0.2s;
        }
        .task-item:hover { background: #f9f9f9; }
        .task-item:last-child { border-bottom: none; }
        .task-checkbox {
            width: 24px;
            height: 24px;
            margin-right: 1rem;
            cursor: pointer;
            accent-color: #667eea;
        }
        .task-title {
            flex: 1;
            font-size: 1rem;
        }
        .task-title.done {
            text-decoration: line-through;
            color: #999;
        }
        .task-delete {
            background: none;
            border: none;
            color: #ff4444;
            cursor: pointer;
            font-size: 1.2rem;
            padding: 0.25rem;
            opacity: 0.5;
            transition: opacity 0.2s;
        }
        .task-delete:hover { opacity: 1; }
        .priority {
            font-size: 0.7rem;
            padding: 0.2rem 0.5rem;
            border-radius: 4px;
            margin-left: 0.5rem;
        }
        .priority-high { background: #ffebee; color: #c62828; }
        .priority-medium { background: #fff3e0; color: #ef6c00; }
        .priority-low { background: #e8f5e9; color: #2e7d32; }
        .empty {
            text-align: center;
            color: #999;
            padding: 2rem;
        }
        .stats {
            display: flex;
            justify-content: space-between;
            margin-top: 1rem;
            padding-top: 1rem;
            border-top: 1px solid #f0f0f0;
            color: #666;
            font-size: 0.9rem;
        }
        .footer-link {
            text-align: center;
            margin-top: 1.5rem;
        }
        .footer-link a {
            color: rgba(255,255,255,0.5);
            font-size: 0.75rem;
            text-decoration: none;
        }
        .footer-link a:hover {
            color: rgba(255,255,255,0.8);
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📝 My Tasks</h1>
        
        <div class="card">
            <form class="add-form" onsubmit="addTask(event)">
                <input type="text" id="newTask" placeholder="Add a task..." autofocus>
                <button type="submit">Add</button>
            </form>
            
            <ul class="task-list" id="taskList">
                <li class="empty">Loading...</li>
            </ul>
            
            <div class="stats">
                <span id="taskCount">0 tasks</span>
                <span id="completedCount">0 completed</span>
            </div>
        </div>
        
        <p class="footer-link"><a href="/explain">How was this built?</a></p>
    </div>
    
    <script>
        const API = '/api/tasks';
        
        async function loadTasks() {
            const res = await fetch(API);
            const data = await res.json();
            renderTasks(data.tasks);
        }
        
        function renderTasks(tasks) {
            const list = document.getElementById('taskList');
            const count = document.getElementById('taskCount');
            const completed = document.getElementById('completedCount');
            
            if (tasks.length === 0) {
                list.innerHTML = '<li class="empty">No tasks yet. Add one above!</li>';
            } else {
                list.innerHTML = tasks.map(task => `
                    <li class="task-item">
                        <input 
                            type="checkbox" 
                            class="task-checkbox"
                            ${task.done ? 'checked' : ''}
                            onchange="toggleTask(${task.id})"
                        >
                        <span class="task-title ${task.done ? 'done' : ''}">${escapeHtml(task.title)}</span>
                        <span class="priority priority-${task.priority}">${task.priority}</span>
                        <button class="task-delete" onclick="deleteTask(${task.id})">×</button>
                    </li>
                `).join('');
            }
            
            count.textContent = `${tasks.length} task${tasks.length !== 1 ? 's' : ''}`;
            completed.textContent = `${tasks.filter(t => t.done).length} completed`;
        }
        
        function escapeHtml(text) {
            const div = document.createElement('div');
            div.textContent = text;
            return div.innerHTML;
        }
        
        async function addTask(e) {
            e.preventDefault();
            const input = document.getElementById('newTask');
            const title = input.value.trim();
            
            if (!title) return;
            
            await fetch(API, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ title, priority: 'medium' })
            });
            
            input.value = '';
            loadTasks();
        }
        
        async function toggleTask(id) {
            await fetch(`${API}/${id}/toggle`, { method: 'POST' });
            loadTasks();
        }
        
        async function deleteTask(id) {
            await fetch(`${API}/${id}`, { method: 'DELETE' });
            loadTasks();
        }
        
        // Initial load
        loadTasks();
    </script>
</body>
</html>
"""

@app.route("/")
def index():
    """Serve the frontend."""
    return render_template_string(HTML_TEMPLATE)

@app.route("/health")
def health():
    """Health check endpoint."""
    return jsonify({"status": "healthy", "version": "1.0.0"})

@app.route("/explain")
def explain():
    """Show how and why this app was built."""
    return render_template_string(EXPLAIN_TEMPLATE)

EXPLAIN_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>How This App Works - Blueprint</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: #1a1a2e;
            color: #eee;
            line-height: 1.6;
            padding: 2rem;
        }
        .container { max-width: 900px; margin: 0 auto; }
        h1 { color: #667eea; margin-bottom: 0.5rem; }
        h2 { color: #764ba2; margin: 2rem 0 1rem; border-bottom: 1px solid #333; padding-bottom: 0.5rem; }
        h3 { color: #888; margin: 1.5rem 0 0.5rem; }
        .subtitle { color: #888; margin-bottom: 2rem; }
        .card {
            background: #16213e;
            border-radius: 12px;
            padding: 1.5rem;
            margin: 1rem 0;
            border-left: 4px solid #667eea;
        }
        .constraint { display: flex; align-items: center; margin: 0.5rem 0; }
        .arrow { color: #667eea; margin: 0 1rem; font-size: 1.5rem; }
        .decision { color: #4ade80; }
        .why { color: #888; font-size: 0.9rem; margin-left: 1rem; }
        code {
            background: #0f0f23;
            padding: 0.2rem 0.5rem;
            border-radius: 4px;
            font-family: 'Consolas', monospace;
        }
        pre {
            background: #0f0f23;
            padding: 1rem;
            border-radius: 8px;
            overflow-x: auto;
            margin: 1rem 0;
        }
        .blocks { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 1rem; }
        .block {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border-radius: 8px;
            padding: 1rem;
        }
        .block-name { font-weight: bold; font-size: 1.1rem; }
        .block-desc { font-size: 0.9rem; opacity: 0.9; }
        .back { 
            display: inline-block;
            color: #667eea;
            text-decoration: none;
            margin-bottom: 1rem;
        }
        .back:hover { text-decoration: underline; }
        .step-num {
            background: #667eea;
            color: white;
            width: 28px;
            height: 28px;
            border-radius: 50%;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            margin-right: 0.5rem;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="container">
        <a href="/" class="back">← Back to App</a>
        <h1>🔍 How This App Works</h1>
        <p class="subtitle">Understanding the architecture so you can modify it yourself</p>
        
        <h2><span class="step-num">1</span> Your Requirements</h2>
        <div class="card">
            <p>You asked for: <strong>"A todo app"</strong></p>
            <p style="margin-top: 1rem;">The system extracted these constraints:</p>
            <ul style="margin: 1rem 0 0 1.5rem;">
                <li>Needs to <strong>store data</strong> → requires storage</li>
                <li>Needs to <strong>list/create/update/delete</strong> → requires CRUD</li>
                <li>Should work in <strong>browser</strong> → requires web backend</li>
                <li>Single user for now → no auth needed (yet)</li>
            </ul>
        </div>
        
        <h2><span class="step-num">2</span> Constraints → Decisions</h2>
        <div class="card">
            <div class="constraint">
                <code>needs_storage=true</code>
                <span class="arrow">→</span>
                <span class="decision">storage_json block</span>
                <span class="why">Simplest for dev. Upgradeable later.</span>
            </div>
            <div class="constraint">
                <code>needs_crud=true</code>
                <span class="arrow">→</span>
                <span class="decision">crud_routes block</span>
                <span class="why">Generates REST endpoints.</span>
            </div>
            <div class="constraint">
                <code>needs_web=true</code>
                <span class="arrow">→</span>
                <span class="decision">backend_flask block</span>
                <span class="why">Simpler than FastAPI for beginners.</span>
            </div>
            <div class="constraint">
                <code>multi_user=false</code>
                <span class="arrow">→</span>
                <span class="decision">No auth block</span>
                <span class="why">Add later if needed.</span>
            </div>
        </div>
        
        <h2><span class="step-num">3</span> The Blocks Used</h2>
        <div class="blocks">
            <div class="block">
                <div class="block-name">🌐 backend_flask</div>
                <div class="block-desc">Web server with routes, handles HTTP requests</div>
            </div>
            <div class="block">
                <div class="block-name">💾 storage_json</div>
                <div class="block-desc">Saves tasks to data/tasks.json file</div>
            </div>
            <div class="block">
                <div class="block-name">🔄 crud_routes</div>
                <div class="block-desc">GET/POST/PUT/DELETE endpoints</div>
            </div>
        </div>
        
        <h2><span class="step-num">4</span> Code Structure</h2>
        <div class="card">
<pre>app.py
├── Lines 1-16:    Flask setup (app, CORS, secret key)
├── Lines 22-42:   Storage functions (load/save JSON)
├── Lines 48-130:  API routes (REST endpoints)
├── Lines 136-280: HTML template (frontend UI)
└── Lines 380-397: Server startup</pre>
        </div>
        
        <h2><span class="step-num">5</span> How to Extend</h2>
        <div class="card">
            <h3>Add a due date field:</h3>
            <pre>task = {
    ...
    "due_date": data.get("due_date"),
}</pre>
            <h3>Add user authentication:</h3>
            <pre>python blueprint.py create "todo app with login"</pre>
            <h3>Switch to SQLite database:</h3>
            <pre>python blueprint.py create "todo app" --storage sqlite</pre>
        </div>
        
        <h2><span class="step-num">6</span> What You Learned</h2>
        <div class="card">
            <p>By studying this app, you now understand:</p>
            <ul style="margin: 1rem 0 0 1.5rem;">
                <li>✅ How Flask apps are structured</li>
                <li>✅ How REST APIs work (GET/POST/PUT/DELETE)</li>
                <li>✅ How to store data in JSON files</li>
                <li>✅ How frontend JavaScript calls backend Python</li>
                <li>✅ Why constraints drive architecture</li>
                <li>✅ How to extend the app yourself</li>
            </ul>
        </div>
        
        <p style="text-align: center; margin-top: 3rem; color: #666;">
            <a href="/" style="color: #667eea;">← Back to My Tasks</a>
        </p>
    </div>
</body>
</html>
"""

# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    print("\n  ✅ Todo app running at: http://localhost:5000\n")
    
    app.run(debug=True, port=5000)
