"""
Test_App - Generated by Blueprint Visual Builder

Description: Test app
Blocks: storage_sqlite, crud_routes
"""

from flask import Flask, request, jsonify, session, redirect


app = Flask(__name__)
app.secret_key = "blueprint-test_app-secret"



import sqlite3
DB_PATH = "test_apps.db"
def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("CREATE TABLE IF NOT EXISTS test_apps (id INTEGER PRIMARY KEY, content TEXT, done INTEGER DEFAULT 0)")
    conn.commit()
    conn.close()
init_db()


# ============================================================================
# API ROUTES
# ============================================================================

@app.route("/")
def home():
    return """
<!DOCTYPE html>
<html>
<head>
    <title>Test_App</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
               background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
               min-height: 100vh; padding: 40px; }
        .container { max-width: 600px; margin: 0 auto; background: white; 
                     border-radius: 16px; padding: 30px; box-shadow: 0 20px 60px rgba(0,0,0,0.3); }
        h1 { color: #333; margin-bottom: 20px; }
        .info { background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px; }
        .info p { margin: 5px 0; color: #666; font-size: 14px; }
        .blocks { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 10px; }
        .block-tag { background: #667eea; color: white; padding: 4px 10px; 
                     border-radius: 12px; font-size: 12px; }
        form { display: flex; gap: 10px; margin-bottom: 20px; }
        input[type="text"] { flex: 1; padding: 12px; border: 2px solid #ddd; 
                             border-radius: 8px; font-size: 16px; }
        input[type="text"]:focus { outline: none; border-color: #667eea; }
        button { background: #667eea; color: white; border: none; padding: 12px 24px;
                 border-radius: 8px; cursor: pointer; font-size: 16px; font-weight: 600; }
        button:hover { background: #5a6fd6; }
        .items { list-style: none; }
        .items li { display: flex; align-items: center; padding: 12px; 
                    background: #f8f9fa; margin-bottom: 8px; border-radius: 8px; }
        .items li span { flex: 1; }
        .delete { background: #e74c3c; padding: 6px 12px; font-size: 12px; }
        footer { margin-top: 30px; text-align: center; }
        footer a { color: #667eea; text-decoration: none; font-size: 13px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Test_App</h1>
        <div class="info">
            <p><strong>Built with Blueprint</strong></p>
            <p>Test app</p>
            <div class="blocks">
                <span class="block-tag">storage_sqlite</span><span class="block-tag">crud_routes</span>
            </div>
        </div>
        <form id="addForm">
            <input type="text" id="content" placeholder="Add new test_app..." required>
            <button type="submit">Add</button>
        </form>
        <ul class="items" id="items"></ul>
        <footer>
            <a href="/explain">How this was built</a>
        </footer>
    </div>
    <script>
        async function load() {
            const r = await fetch('/api/test_apps');
            const data = await r.json();
            const ul = document.getElementById('items');
            ul.innerHTML = data.test_apps.map((item, i) => 
                `<li><span>${item.content || item}</span>
                 <button class="delete" onclick="del(${i})">Delete</button></li>`
            ).join('');
        }
        document.getElementById('addForm').onsubmit = async (e) => {
            e.preventDefault();
            const content = document.getElementById('content').value;
            await fetch('/api/test_apps', {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({content})
            });
            document.getElementById('content').value = '';
            load();
        };
        async function del(idx) {
            await fetch(`/api/test_apps/${idx}`, {method: 'DELETE'});
            load();
        }
        load();
    </script>
</body>
</html>
    """

@app.route("/api/test_apps", methods=["GET"])
def list_items():
    return jsonify({"test_apps": items})

@app.route("/api/test_apps", methods=["POST"])
def add_item():
    data = request.json or {}
    items.append({"content": data.get("content", ""), "done": False})
    return jsonify({"success": True, "count": len(items)})

@app.route("/api/test_apps/<int:idx>", methods=["DELETE"])
def delete_item(idx):
    if 0 <= idx < len(items):
        items.pop(idx)
    return jsonify({"success": True})

@app.route("/explain")
def explain():
    return """
<!DOCTYPE html>
<html>
<head>
    <title>How Test_App Was Built</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: #f8f9fa; padding: 40px; }
        .container { max-width: 800px; margin: 0 auto; background: white;
                     border-radius: 16px; padding: 40px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }
        h1 { color: #333; margin-bottom: 20px; }
        h2 { color: #667eea; margin-top: 30px; }
        p { color: #555; line-height: 1.7; }
        code { background: #f0f0f0; padding: 2px 6px; border-radius: 4px; }
        pre { background: #2d3436; color: #dfe6e9; padding: 20px; border-radius: 8px;
              overflow-x: auto; }
        .back { display: inline-block; margin-top: 20px; color: #667eea; text-decoration: none; }
    </style>
</head>
<body>
    <div class="container">
        <h1>How Test_App Was Built</h1>
        <p>This app was generated using the <strong>Blueprint Visual Builder</strong>, 
           a constraint-based scaffolding system.</p>
        
        <h2>Selected Blocks</h2>
        <p>The following blocks were composed to create this app:</p>
        <ul>
            <li><code>storage_sqlite</code> - SQLite database storage for production-ready local apps</li><li><code>crud_routes</code> - Automatic REST endpoints for any entity</li>
        </ul>
        
        <h2>Architecture</h2>
        <p>Blueprint uses <strong>compositional blocks</strong> that declare what they 
           require and provide. Blocks auto-connect based on port matching:</p>
        <ul>
            <li>Each block has <strong>requires</strong> ports (dependencies)</li>
            <li>Each block has <strong>provides</strong> ports (capabilities)</li>
            <li>The constraint solver ensures compatibility</li>
        </ul>
        
        <h2>Generated Files</h2>
        <pre>
output/test_app/
  app.py          # This Flask application
  requirements.txt  # Python dependencies
        </pre>
        
        <a href="/" class="back">Back to app</a>
    </div>
</body>
</html>
    """

if __name__ == "__main__":
    print("Starting Test_App...")
    print("Open: http://localhost:5000")
    app.run(debug=True, port=5000)
