"""Project manager - Handles code generation, file writing, and exports."""

import os
import json
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, Any


class ProjectManager:
    """Manages generated app projects."""
    
    def __init__(self, workspace_root: Path = None):
        self.workspace_root = workspace_root or Path.home() / "AppForge"
        self.workspace_root.mkdir(exist_ok=True)
    
    def create_project(self, app_name: str, description: str, answers: Dict[str, bool], 
                      app_py: str, requirements_txt: str, index_html: str) -> Path:
        """Create a new app project on disk."""
        
        # Sanitize app name
        safe_name = "".join(c for c in app_name if c.isalnum() or c in "-_").lower()
        project_path = self.workspace_root / safe_name
        
       # Create structure
        project_path.mkdir(parents=True, exist_ok=True)
        (project_path / "templates").mkdir(exist_ok=True)
        (project_path / "static").mkdir(exist_ok=True)
        
        # Write files
        (project_path / "app.py").write_text(app_py, encoding="utf-8")
        (project_path / "requirements.txt").write_text(requirements_txt, encoding="utf-8")
        (project_path / "templates" / "index.html").write_text(index_html, encoding="utf-8")
        
        # Write metadata
        metadata = {
            "name": app_name,
            "description": description,
            "answers": answers,
            "created_at": datetime.now().isoformat(),
        }
        (project_path / ".appforge.json").write_text(json.dumps(metadata, indent=2))
        
        # Write .gitignore
        gitignore = """__pycache__/
*.pyc
*.db
.venv/
venv/
.env
.DS_Store
"""
        (project_path / ".gitignore").write_text(gitignore)
        
        # Write README
        readme = f"""# {app_name}

Generated by App Forge.

## Setup

```bash
python -m venv .venv
.venv\\Scripts\\activate  # Windows
source .venv/bin/activate  # Mac/Linux
pip install -r requirements.txt
python app.py
```

Open http://127.0.0.1:5000

## About This App

{description}

### Features

"""
        for key, val in answers.items():
            if val:
                readme += f"- {key.replace('_', ' ').title()}\n"
        
        (project_path / "README.md").write_text(readme)
        
        return project_path
    
    def init_git(self, project_path: Path, remote_url: str = None) -> bool:
        """Initialize git and optionally push to GitHub."""
        try:
            cwd = str(project_path)
            
            # Init git
            subprocess.run(["git", "init"], check=True, capture_output=True, cwd=cwd)
            subprocess.run(["git", "config", "user.email", "appforge@local"], check=True, capture_output=True, cwd=cwd)
            subprocess.run(["git", "config", "user.name", "AppForge"], check=True, capture_output=True, cwd=cwd)
            subprocess.run(["git", "add", "."], check=True, capture_output=True, cwd=cwd)
            subprocess.run(["git", "commit", "-m", "Initial commit: Generated by App Forge"], 
                         check=True, capture_output=True, cwd=cwd)
            
            # Add remote if provided
            if remote_url:
                subprocess.run(["git", "remote", "add", "origin", remote_url], check=True, capture_output=True, cwd=cwd)
                subprocess.run(["git", "branch", "-M", "main"], check=True, capture_output=True, cwd=cwd)
                subprocess.run(["git", "push", "-u", "origin", "main"], check=True, capture_output=True, cwd=cwd)
            
            return True
        except subprocess.CalledProcessError as e:
            print(f"Git error: {e}")
            return False
    
    @staticmethod
    def get_projects(workspace_root: Path = None) -> list:
        """List all projects in workspace."""
        workspace = workspace_root or Path.home() / "AppForge"
        if not workspace.exists():
            return []
        
        projects = []
        for item in workspace.iterdir():
            if item.is_dir() and (item / ".appforge.json").exists():
                meta_file = item / ".appforge.json"
                meta = json.loads(meta_file.read_text())
                projects.append({
                    "path": str(item),
                    "name": meta.get("name"),
                    "description": meta.get("description"),
                })
        
        return projects


# Singleton
manager = ProjectManager()
