"""
Note App - Generated by Blueprint
Description: notes app

Run with: python app.py
Open: http://localhost:5000
"""

from flask import Flask, request, jsonify, render_template_string
from flask_cors import CORS
from datetime import datetime
import json
import os

app = Flask(__name__)
CORS(app)
app.secret_key = os.environ.get("SECRET_KEY", "dev-secret-change-in-prod")

# Storage
DATA_FILE = "data/notes.json"

def ensure_data():
    os.makedirs("data", exist_ok=True)
    if not os.path.exists(DATA_FILE):
        with open(DATA_FILE, "w") as f:
            json.dump([], f)

def load_items():
    ensure_data()
    with open(DATA_FILE, "r") as f:
        return json.load(f)

def save_items(items):
    ensure_data()
    with open(DATA_FILE, "w") as f:
        json.dump(items, f, indent=2, default=str)

def get_next_id():
    items = load_items()
    return max([i["id"] for i in items], default=0) + 1

# API Routes
@app.route("/api/notes", methods=["GET"])
def list_items():
    return jsonify({"items": load_items()})

@app.route("/api/notes", methods=["POST"])
def create_item():
    data = request.get_json()
    if not data or not data.get("title"):
        return jsonify({"error": "Title required"}), 400
    
    item = {
        "id": get_next_id(),
        "title": data["title"],
        "done": False,
        "created_at": datetime.now().isoformat(),
    }
    items = load_items()
    items.append(item)
    save_items(items)
    return jsonify(item), 201

@app.route("/api/notes/<int:item_id>", methods=["DELETE"])
def delete_item(item_id):
    items = [i for i in load_items() if i["id"] != item_id]
    save_items(items)
    return "", 204

@app.route("/api/notes/<int:item_id>/toggle", methods=["POST"])
def toggle_item(item_id):
    items = load_items()
    for item in items:
        if item["id"] == item_id:
            item["done"] = not item["done"]
            save_items(items)
            return jsonify(item)
    return jsonify({"error": "Not found"}), 404

# Frontend
@app.route("/")
def index():
    return render_template_string(HTML)

HTML = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Notes</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: system-ui, sans-serif; background: linear-gradient(135deg, #667eea, #764ba2); min-height: 100vh; padding: 2rem; }
        .container { max-width: 500px; margin: 0 auto; }
        h1 { color: white; text-align: center; margin-bottom: 1.5rem; }
        .card { background: white; border-radius: 12px; padding: 1.5rem; box-shadow: 0 10px 40px rgba(0,0,0,0.2); }
        .add-form { display: flex; gap: 0.5rem; margin-bottom: 1rem; }
        .add-form input { flex: 1; padding: 0.75rem; border: 2px solid #e0e0e0; border-radius: 8px; font-size: 1rem; }
        .add-form input:focus { outline: none; border-color: #667eea; }
        .add-form button { padding: 0.75rem 1.25rem; background: #667eea; color: white; border: none; border-radius: 8px; cursor: pointer; }
        .list { list-style: none; }
        .item { display: flex; align-items: center; padding: 0.75rem; border-bottom: 1px solid #f0f0f0; }
        .item:last-child { border-bottom: none; }
        .item input { margin-right: 0.75rem; width: 20px; height: 20px; }
        .item span { flex: 1; }
        .item.done span { text-decoration: line-through; color: #999; }
        .item button { background: none; border: none; color: #ff4444; cursor: pointer; font-size: 1.2rem; }
        .empty { text-align: center; color: #999; padding: 1rem; }
    </style>
</head>
<body>
    <div class="container">
        <h1>My Notes</h1>
        <div class="card">
            <form class="add-form" onsubmit="add(event)">
                <input type="text" id="input" placeholder="Add a note..." autofocus>
                <button type="submit">Add</button>
            </form>
            <ul class="list" id="list"></ul>
        </div>
    </div>
    <script>
        const API = '/api/notes';
        
        async function load() {
            const r = await fetch(API);
            const data = await r.json();
            const list = document.getElementById('list');
            if (data.items.length === 0) {
                list.innerHTML = '<li class="empty">No notes yet</li>';
                return;
            }
            list.innerHTML = data.items.map(i => `
                <li class="item ${i.done ? 'done' : ''}">
                    <input type="checkbox" ${i.done ? 'checked' : ''} onchange="toggle(${i.id})">
                    <span>${i.title}</span>
                    <button onclick="del(${i.id})">✕</button>
                </li>
            `).join('');
        }
        
        async function add(e) {
            e.preventDefault();
            const input = document.getElementById('input');
            if (!input.value.trim()) return;
            await fetch(API, {
                method: 'POST',
                headers: {'Content-Type': 'application/json'},
                body: JSON.stringify({title: input.value})
            });
            input.value = '';
            load();
        }
        
        async function toggle(id) {
            await fetch(`${API}/${id}/toggle`, {method: 'POST'});
            load();
        }
        
        async function del(id) {
            await fetch(`${API}/${id}`, {method: 'DELETE'});
            load();
        }
        
        load();
    </script>
</body>
</html>
"""

# How it was built page
@app.route("/explain")
def explain():
    return render_template_string(EXPLAIN)

EXPLAIN = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>How This Was Built</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: system-ui, sans-serif; background: #1a1a2e; color: #eee; line-height: 1.7; padding: 2rem; }
        .container { max-width: 700px; margin: 0 auto; }
        h1 { color: #667eea; margin-bottom: 0.5rem; }
        h2 { color: #a78bfa; margin: 2rem 0 1rem; font-size: 1.2rem; }
        .card { background: #16213e; border-radius: 12px; padding: 1.5rem; margin: 1rem 0; border-left: 4px solid #667eea; }
        a { color: #667eea; }
        code { background: #0f0f23; padding: 0.2rem 0.4rem; border-radius: 4px; font-size: 0.9rem; }
        .step { display: flex; align-items: flex-start; margin: 0.75rem 0; }
        .num { background: #667eea; color: white; width: 24px; height: 24px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin-right: 0.75rem; font-size: 0.8rem; flex-shrink: 0; }
        ul { margin-left: 1.5rem; margin-top: 0.5rem; }
        li { margin: 0.25rem 0; }
    </style>
</head>
<body>
    <div class="container">
        <p><a href="/">Back to app</a></p>
        <h1>How This App Was Built</h1>
        <p style="color: #888;">Understanding the architecture so you can modify it</p>
        
        <h2>Your Request</h2>
        <div class="card">
            <p>You said: <strong>"notes app"</strong></p>
            <p style="margin-top: 0.5rem; color: #888;">The system created a Note app with storage and API.</p>
        </div>
        
        <h2>What Was Built</h2>
        <div class="card">
            <div class="step"><span class="num">1</span><span><strong>Flask web server</strong> - handles HTTP requests</span></div>
            <div class="step"><span class="num">2</span><span><strong>JSON file storage</strong> - saves data to <code>data/notes.json</code></span></div>
            <div class="step"><span class="num">3</span><span><strong>REST API</strong> - create, read, update, delete operations</span></div>
            <div class="step"><span class="num">4</span><span><strong>HTML frontend</strong> - the interface you see</span></div>
        </div>
        
        <h2>The Code Structure</h2>
        <div class="card">
            <p><code>app.py</code> contains everything:</p>
            <ul>
                <li><strong>Lines 1-20:</strong> Setup (Flask, CORS, config)</li>
                <li><strong>Lines 22-45:</strong> Storage functions (load/save JSON)</li>
                <li><strong>Lines 47-80:</strong> API routes (GET, POST, DELETE)</li>
                <li><strong>Lines 82-end:</strong> HTML template with JavaScript</li>
            </ul>
        </div>
        
        <h2>How to Modify</h2>
        <div class="card">
            <p><strong>Add a field</strong> (e.g., description):</p>
            <p style="margin-top: 0.5rem;"><code>item = {"title": ..., "description": data.get("description"), ...}</code></p>
            
            <p style="margin-top: 1rem;"><strong>Change the look:</strong></p>
            <p style="margin-top: 0.5rem;">Edit the CSS in the <code>&lt;style&gt;</code> section</p>
            
            <p style="margin-top: 1rem;"><strong>Add features:</strong></p>
            <p style="margin-top: 0.5rem;">Copy the pattern from existing routes to add new ones</p>
        </div>
        
        <h2>Why These Choices?</h2>
        <div class="card">
            <ul>
                <li><strong>JSON storage</strong> - Simple, no setup needed. Upgrade to SQLite for more power.</li>
                <li><strong>Flask</strong> - Easy to understand. Same patterns work in bigger frameworks.</li>
                <li><strong>Single file</strong> - Everything in one place for learning. Split later if needed.</li>
            </ul>
        </div>
        
        <p style="text-align: center; margin-top: 2rem;"><a href="/">Back to My Notes</a></p>
    </div>
</body>
</html>
"""

if __name__ == "__main__":
    print(f"\n  App running at: http://localhost:5000\n")
    print(f"  See how it works: http://localhost:5000/explain\n")
    app.run(debug=True, port=5000)
