"""
Auto-generated Flask Application

Generated by Intelligent Scaffolder v1.0
Stack: flask
Blocks: Basic Authentication, CRDT Sync Engine, JSON File Storage, SQLite Storage
Entities: User, Task, Team
"""

from flask import Flask

from auth_basic import create_auth_routes
from storage_json import storage
from storage_sqlite import storage
from routes.user_routes import user_bp
from routes.task_routes import task_bp
from routes.team_routes import team_bp


def create_app():
    """Application factory."""
    app = Flask(__name__)
    app.secret_key = "change-me-in-production"

    # Authentication
    create_auth_routes(app, storage)

    # Entity routes
    app.register_blueprint(user_bp)
    app.register_blueprint(task_bp)
    app.register_blueprint(team_bp)

    @app.route("/")
    def index():
        return {"status": "ok", "message": "API is running"}

    return app


if __name__ == "__main__":
    app = create_app()
    app.run(debug=True)