"""Show summary of generated demo apps."""
import os
import json

apps_dir = os.path.join(os.path.dirname(__file__), 'demo_apps')
summary = []

for app in sorted(os.listdir(apps_dir)):
    app_path = os.path.join(apps_dir, app)
    if os.path.isdir(app_path):
        info_path = os.path.join(app_path, 'app_info.json')
        if os.path.exists(info_path):
            info = json.load(open(info_path))
            lines = 0
            for f in os.listdir(app_path):
                fpath = os.path.join(app_path, f)
                if f.endswith(('.py', '.html')) and os.path.isfile(fpath):
                    lines += len(open(fpath, encoding='utf-8').readlines())
                elif os.path.isdir(fpath):  # templates folder
                    for sf in os.listdir(fpath):
                        if sf.endswith('.html'):
                            lines += len(open(os.path.join(fpath, sf), encoding='utf-8').readlines())
            summary.append({
                'name': info.get('name'),
                'complexity': info.get('complexity'),
                'template': info.get('template'),
                'lines': lines
            })

print('='*70)
print('         10 DEMO APPS GENERATED BY APP FORGE')
print('='*70)
print(f"{'#':<3} {'Name':<25} {'Complexity':<12} {'Template':<18} {'Lines':>6}")
print('-'*70)
for i, app in enumerate(summary, 1):
    print(f"{i:<3} {app['name']:<25} {app['complexity']:<12} {app['template']:<18} {app['lines']:>6}")
print('-'*70)
print(f"{'Total:':<40} {'':<18} {sum(a['lines'] for a in summary):>6} lines")
print()
print("Run any app with: python demo_apps/<app_name>/app.py")
print("Open HTML apps directly in browser: demo_apps/<app_name>/index.html")
