"""
Visual Blueprint Builder - Simple Web UI for App Generation

A clean, working visual interface for creating apps with blocks.
No dependencies on archived features - just the core system.

Run: python visual_builder.py
Opens: http://localhost:5000
"""

import os
import sys
import json
import webbrowser
import threading
from pathlib import Path
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.parse import urlparse

# Add parent for imports
sys.path.insert(0, str(Path(__file__).parent))

from blocks import BLOCKS

PORT = 5000
OUTPUT_DIR = Path(__file__).parent / "output"


def get_blocks_json():
    """Get all blocks as JSON for the frontend."""
    blocks = []
    for block_id, block in BLOCKS.items():
        blocks.append({
            "id": block_id,
            "name": block.name,
            "description": block.description,
            "requires": [{"name": p.name, "type": p.type} for p in block.requires],
            "provides": [{"name": p.name, "type": p.type} for p in block.provides],
            "dependencies": block.dependencies.get("flask", [])
        })
    return blocks


def generate_app(project_name: str, selected_blocks: list, description: str = "") -> dict:
    """Generate an app from selected blocks."""
    output_path = OUTPUT_DIR / project_name.lower().replace(" ", "_")
    output_path.mkdir(parents=True, exist_ok=True)
    
    # Generate app code based on description and blocks
    app_name = project_name.title()
    entity = project_name.lower().split()[0] if project_name else "item"
    
    # Build routes based on blocks
    has_auth = "auth_basic" in selected_blocks or "auth_oauth" in selected_blocks
    has_storage = any(b.startswith("storage_") for b in selected_blocks)
    has_crud = "crud_routes" in selected_blocks
    
    auth_import = ""
    auth_check = ""
    if has_auth:
        auth_import = "from functools import wraps"
        auth_check = '''
def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get('user'):
            return redirect('/login')
        return f(*args, **kwargs)
    return decorated
'''
    
    storage_code = "items = []  # In-memory storage"
    if "storage_sqlite" in selected_blocks:
        storage_code = '''import sqlite3
DB_PATH = "{entity}s.db"
def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("CREATE TABLE IF NOT EXISTS {entity}s (id INTEGER PRIMARY KEY, content TEXT, done INTEGER DEFAULT 0)")
    conn.commit()
    conn.close()
init_db()
'''.format(entity=entity)
    
    # Collect dependencies
    deps = ["flask"]
    for block_id in selected_blocks:
        if block_id in BLOCKS:
            block_deps = BLOCKS[block_id].dependencies.get("flask", [])
            deps.extend(block_deps)
    deps = list(set(deps))
    
    # Generate the app code
    app_code = f'''"""
{app_name} - Generated by Blueprint Visual Builder

Description: {description or "A web application built with Blueprint blocks."}
Blocks: {", ".join(selected_blocks) if selected_blocks else "minimal"}
"""

from flask import Flask, request, jsonify, session, redirect
{auth_import}

app = Flask(__name__)
app.secret_key = "blueprint-{project_name.lower().replace(" ", "-")}-secret"

{auth_check}

{storage_code}

# ============================================================================
# API ROUTES
# ============================================================================

@app.route("/")
def home():
    return """
<!DOCTYPE html>
<html>
<head>
    <title>{app_name}</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; 
               background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
               min-height: 100vh; padding: 40px; }}
        .container {{ max-width: 600px; margin: 0 auto; background: white; 
                     border-radius: 16px; padding: 30px; box-shadow: 0 20px 60px rgba(0,0,0,0.3); }}
        h1 {{ color: #333; margin-bottom: 20px; }}
        .info {{ background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 20px; }}
        .info p {{ margin: 5px 0; color: #666; font-size: 14px; }}
        .blocks {{ display: flex; flex-wrap: wrap; gap: 8px; margin-top: 10px; }}
        .block-tag {{ background: #667eea; color: white; padding: 4px 10px; 
                     border-radius: 12px; font-size: 12px; }}
        form {{ display: flex; gap: 10px; margin-bottom: 20px; }}
        input[type="text"] {{ flex: 1; padding: 12px; border: 2px solid #ddd; 
                             border-radius: 8px; font-size: 16px; }}
        input[type="text"]:focus {{ outline: none; border-color: #667eea; }}
        button {{ background: #667eea; color: white; border: none; padding: 12px 24px;
                 border-radius: 8px; cursor: pointer; font-size: 16px; font-weight: 600; }}
        button:hover {{ background: #5a6fd6; }}
        .items {{ list-style: none; }}
        .items li {{ display: flex; align-items: center; padding: 12px; 
                    background: #f8f9fa; margin-bottom: 8px; border-radius: 8px; }}
        .items li span {{ flex: 1; }}
        .delete {{ background: #e74c3c; padding: 6px 12px; font-size: 12px; }}
        footer {{ margin-top: 30px; text-align: center; }}
        footer a {{ color: #667eea; text-decoration: none; font-size: 13px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{app_name}</h1>
        <div class="info">
            <p><strong>Built with Blueprint</strong></p>
            <p>{description or "A web application generated from composable blocks."}</p>
            <div class="blocks">
                {"".join(f'<span class="block-tag">{b}</span>' for b in selected_blocks) if selected_blocks else '<span class="block-tag">minimal</span>'}
            </div>
        </div>
        <form id="addForm">
            <input type="text" id="content" placeholder="Add new {entity}..." required>
            <button type="submit">Add</button>
        </form>
        <ul class="items" id="items"></ul>
        <footer>
            <a href="/explain">How this was built</a>
        </footer>
    </div>
    <script>
        async function load() {{
            const r = await fetch('/api/{entity}s');
            const data = await r.json();
            const ul = document.getElementById('items');
            ul.innerHTML = data.{entity}s.map((item, i) => 
                `<li><span>${{item.content || item}}</span>
                 <button class="delete" onclick="del(${{i}})">Delete</button></li>`
            ).join('');
        }}
        document.getElementById('addForm').onsubmit = async (e) => {{
            e.preventDefault();
            const content = document.getElementById('content').value;
            await fetch('/api/{entity}s', {{
                method: 'POST',
                headers: {{'Content-Type': 'application/json'}},
                body: JSON.stringify({{content}})
            }});
            document.getElementById('content').value = '';
            load();
        }};
        async function del(idx) {{
            await fetch(`/api/{entity}s/${{idx}}`, {{method: 'DELETE'}});
            load();
        }}
        load();
    </script>
</body>
</html>
    """

@app.route("/api/{entity}s", methods=["GET"])
def list_items():
    return jsonify({{"{entity}s": items}})

@app.route("/api/{entity}s", methods=["POST"])
def add_item():
    data = request.json or {{}}
    items.append({{"content": data.get("content", ""), "done": False}})
    return jsonify({{"success": True, "count": len(items)}})

@app.route("/api/{entity}s/<int:idx>", methods=["DELETE"])
def delete_item(idx):
    if 0 <= idx < len(items):
        items.pop(idx)
    return jsonify({{"success": True}})

@app.route("/explain")
def explain():
    return """
<!DOCTYPE html>
<html>
<head>
    <title>How {app_name} Was Built</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
               background: #f8f9fa; padding: 40px; }}
        .container {{ max-width: 800px; margin: 0 auto; background: white;
                     border-radius: 16px; padding: 40px; box-shadow: 0 4px 20px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; margin-bottom: 20px; }}
        h2 {{ color: #667eea; margin-top: 30px; }}
        p {{ color: #555; line-height: 1.7; }}
        code {{ background: #f0f0f0; padding: 2px 6px; border-radius: 4px; }}
        pre {{ background: #2d3436; color: #dfe6e9; padding: 20px; border-radius: 8px;
              overflow-x: auto; }}
        .back {{ display: inline-block; margin-top: 20px; color: #667eea; text-decoration: none; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>How {app_name} Was Built</h1>
        <p>This app was generated using the <strong>Blueprint Visual Builder</strong>, 
           a constraint-based scaffolding system.</p>
        
        <h2>Selected Blocks</h2>
        <p>The following blocks were composed to create this app:</p>
        <ul>
            {"".join(f"<li><code>{b}</code> - {BLOCKS[b].description if b in BLOCKS else 'Custom block'}</li>" for b in selected_blocks) if selected_blocks else "<li>Minimal template (no blocks)</li>"}
        </ul>
        
        <h2>Architecture</h2>
        <p>Blueprint uses <strong>compositional blocks</strong> that declare what they 
           require and provide. Blocks auto-connect based on port matching:</p>
        <ul>
            <li>Each block has <strong>requires</strong> ports (dependencies)</li>
            <li>Each block has <strong>provides</strong> ports (capabilities)</li>
            <li>The constraint solver ensures compatibility</li>
        </ul>
        
        <h2>Generated Files</h2>
        <pre>
output/{project_name.lower().replace(" ", "_")}/
  app.py          # This Flask application
  requirements.txt  # Python dependencies
        </pre>
        
        <a href="/" class="back">Back to app</a>
    </div>
</body>
</html>
    """

if __name__ == "__main__":
    print("Starting {app_name}...")
    print("Open: http://localhost:5000")
    app.run(debug=True, port=5000)
'''
    
    # Write app.py
    app_file = output_path / "app.py"
    app_file.write_text(app_code, encoding='utf-8')
    
    # Write requirements.txt
    req_file = output_path / "requirements.txt"
    req_file.write_text("\n".join(deps), encoding='utf-8')
    
    return {
        "success": True,
        "path": str(output_path),
        "files": ["app.py", "requirements.txt"],
        "run_command": f"cd {output_path} && python app.py"
    }


def get_code_preview(project_name: str, selected_blocks: list, description: str = "") -> str:
    """Generate a preview of the app code without writing files."""
    app_name = project_name.title() if project_name else "My App"
    entity = project_name.lower().split()[0] if project_name else "item"
    
    # Build feature flags
    has_auth = "auth_basic" in selected_blocks or "auth_oauth" in selected_blocks
    has_sqlite = "storage_sqlite" in selected_blocks
    has_postgres = "storage_postgres" in selected_blocks
    has_redis = "cache_redis" in selected_blocks
    has_websocket = "websocket_basic" in selected_blocks
    
    imports = ["from flask import Flask, request, jsonify, session, redirect"]
    if has_auth:
        imports.append("from functools import wraps")
    if has_sqlite:
        imports.append("import sqlite3")
    if has_postgres:
        imports.append("import psycopg2")
    if has_websocket:
        imports.append("from flask_socketio import SocketIO")
    
    preview = f'''"""
{app_name} - Generated by Blueprint Visual Builder

Description: {description or "A web application built with Blueprint blocks."}
Blocks: {", ".join(selected_blocks) if selected_blocks else "minimal"}
"""

{chr(10).join(imports)}

app = Flask(__name__)
app.secret_key = "blueprint-generated-secret"
'''
    
    if has_websocket:
        preview += "socketio = SocketIO(app)\n"
    
    if has_auth:
        preview += '''
def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get('user'):
            return redirect('/login')
        return f(*args, **kwargs)
    return decorated
'''
    
    if has_sqlite:
        preview += f'''
# SQLite Storage
DB_PATH = "{entity}s.db"
def init_db():
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute("CREATE TABLE IF NOT EXISTS {entity}s (id INTEGER PRIMARY KEY, content TEXT)")
    conn.commit()
    conn.close()
init_db()
'''
    elif has_postgres:
        preview += '''
# PostgreSQL Storage  
import os
DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://localhost/myapp")
'''
    else:
        preview += "\n# In-memory storage\nitems = []\n"
    
    if has_redis:
        preview += '''
# Redis Cache
import redis
cache = redis.Redis(host='localhost', port=6379, db=0)
'''
    
    preview += f'''
@app.route("/")
def home():
    return "Welcome to {app_name}!"

@app.route("/api/{entity}s", methods=["GET"])
def list_items():
    return jsonify({{"{entity}s": items}})

@app.route("/api/{entity}s", methods=["POST"])
def add_item():
    data = request.json or {{}}
    items.append({{"content": data.get("content", "")}})
    return jsonify({{"success": True}})
'''
    
    if has_websocket:
        preview += '''
@socketio.on('message')
def handle_message(data):
    socketio.emit('broadcast', data)
'''
    
    preview += '''
if __name__ == "__main__":
    print("Starting server...")
    app.run(debug=True, port=5000)
'''
    
    return preview


class BuilderHandler(SimpleHTTPRequestHandler):
    """HTTP handler for the visual builder."""
    
    def do_GET(self):
        parsed = urlparse(self.path)
        
        if parsed.path == "/":
            # Serve the visual builder UI
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(get_builder_html().encode())
            return
        
        if parsed.path == "/api/blocks":
            self.send_json({"blocks": get_blocks_json()})
            return
        
        self.send_error(404)
    
    def do_POST(self):
        parsed = urlparse(self.path)
        
        if parsed.path == "/api/generate":
            content_length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(content_length).decode()
            data = json.loads(body) if body else {}
            
            result = generate_app(
                project_name=data.get("name", "my_app"),
                selected_blocks=data.get("blocks", []),
                description=data.get("description", "")
            )
            self.send_json(result)
            return
        
        if parsed.path == "/api/preview":
            content_length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(content_length).decode()
            data = json.loads(body) if body else {}
            
            preview = get_code_preview(
                project_name=data.get("name", "my_app"),
                selected_blocks=data.get("blocks", []),
                description=data.get("description", "")
            )
            self.send_json({"code": preview})
            return
        
        self.send_error(404)
    
    def send_json(self, data):
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(json.dumps(data).encode())
    
    def log_message(self, format, *args):
        # Quieter logging
        pass


def get_builder_html():
    """Return the visual builder HTML."""
    return '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blueprint Visual Builder</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        
        :root {
            --primary: #667eea;
            --primary-dark: #5a6fd6;
            --success: #00b894;
            --danger: #e74c3c;
            --bg: #1a1a2e;
            --bg-card: #16213e;
            --text: #e0e0e0;
            --text-dim: #888;
            --border: rgba(255,255,255,0.1);
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: linear-gradient(135deg, var(--bg) 0%, var(--bg-card) 100%);
            min-height: 100vh;
            color: var(--text);
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 30px;
        }
        
        header {
            text-align: center;
            margin-bottom: 40px;
        }
        
        h1 {
            font-size: 2.5em;
            background: linear-gradient(135deg, var(--primary), #764ba2);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            margin-bottom: 10px;
        }
        
        .subtitle {
            color: var(--text-dim);
            font-size: 1.1em;
        }
        
        .main-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 30px;
        }
        
        .panel {
            background: var(--bg-card);
            border-radius: 16px;
            padding: 25px;
            border: 1px solid var(--border);
        }
        
        .panel h2 {
            font-size: 1.3em;
            margin-bottom: 20px;
            display: flex;
            align-items: center;
            gap: 10px;
        }
        
        .panel h2::before {
            content: "";
            width: 4px;
            height: 24px;
            background: var(--primary);
            border-radius: 2px;
        }
        
        /* Project Config */
        .form-group {
            margin-bottom: 20px;
        }
        
        label {
            display: block;
            margin-bottom: 8px;
            font-size: 0.9em;
            color: var(--text-dim);
        }
        
        input[type="text"], textarea {
            width: 100%;
            padding: 12px 16px;
            background: rgba(0,0,0,0.3);
            border: 2px solid var(--border);
            border-radius: 10px;
            color: var(--text);
            font-size: 1em;
            transition: border-color 0.2s;
        }
        
        input[type="text"]:focus, textarea:focus {
            outline: none;
            border-color: var(--primary);
        }
        
        textarea {
            resize: vertical;
            min-height: 80px;
        }
        
        /* Blocks */
        .blocks-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 12px;
            max-height: 400px;
            overflow-y: auto;
            padding-right: 10px;
        }
        
        .block-card {
            background: rgba(0,0,0,0.3);
            border: 2px solid var(--border);
            border-radius: 12px;
            padding: 15px;
            cursor: pointer;
            transition: all 0.2s;
        }
        
        .block-card:hover {
            border-color: var(--primary);
            transform: translateY(-2px);
        }
        
        .block-card.selected {
            border-color: var(--success);
            background: rgba(0, 184, 148, 0.1);
        }
        
        .block-card .name {
            font-weight: 600;
            margin-bottom: 5px;
        }
        
        .block-card .desc {
            font-size: 0.8em;
            color: var(--text-dim);
            line-height: 1.4;
        }
        
        .block-card .ports {
            margin-top: 10px;
            display: flex;
            gap: 5px;
            flex-wrap: wrap;
        }
        
        .port-tag {
            font-size: 0.7em;
            padding: 2px 6px;
            border-radius: 8px;
            background: rgba(102, 126, 234, 0.2);
            color: var(--primary);
        }
        
        .port-tag.provides {
            background: rgba(0, 184, 148, 0.2);
            color: var(--success);
        }
        
        /* Selected blocks summary */
        .selected-summary {
            margin-top: 20px;
            padding: 15px;
            background: rgba(0,0,0,0.2);
            border-radius: 10px;
        }
        
        .selected-summary h3 {
            font-size: 0.9em;
            color: var(--text-dim);
            margin-bottom: 10px;
        }
        
        .selected-tags {
            display: flex;
            flex-wrap: wrap;
            gap: 8px;
        }
        
        .selected-tag {
            background: var(--success);
            color: white;
            padding: 5px 12px;
            border-radius: 15px;
            font-size: 0.85em;
            display: flex;
            align-items: center;
            gap: 6px;
        }
        
        .selected-tag .remove {
            cursor: pointer;
            opacity: 0.7;
        }
        
        .selected-tag .remove:hover {
            opacity: 1;
        }
        
        /* Generate button */
        .generate-section {
            margin-top: 30px;
            text-align: center;
        }
        
        .btn-generate {
            background: linear-gradient(135deg, var(--primary), #764ba2);
            color: white;
            border: none;
            padding: 16px 40px;
            font-size: 1.2em;
            font-weight: 600;
            border-radius: 12px;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
        }
        
        .btn-generate:hover {
            transform: translateY(-2px);
            box-shadow: 0 10px 30px rgba(102, 126, 234, 0.4);
        }
        
        .btn-generate:disabled {
            opacity: 0.5;
            cursor: not-allowed;
            transform: none;
        }
        
        /* Result panel */
        .result-panel {
            margin-top: 30px;
            display: none;
        }
        
        .result-panel.show {
            display: block;
        }
        
        .result-content {
            background: rgba(0, 184, 148, 0.1);
            border: 1px solid var(--success);
            border-radius: 12px;
            padding: 20px;
        }
        
        .result-content h3 {
            color: var(--success);
            margin-bottom: 15px;
        }
        
        .result-content code {
            background: rgba(0,0,0,0.3);
            padding: 10px 15px;
            border-radius: 8px;
            display: block;
            font-family: 'Consolas', 'Monaco', monospace;
            margin: 10px 0;
            overflow-x: auto;
        }
        
        .btn-run {
            background: var(--success);
            color: white;
            border: none;
            padding: 12px 24px;
            font-size: 1em;
            font-weight: 600;
            border-radius: 8px;
            cursor: pointer;
            margin-top: 15px;
        }
        
        .btn-run:hover {
            background: #00a884;
        }
        
        /* Code Preview */
        .preview-panel {
            background: var(--bg-card);
        }
        
        .code-preview {
            background: #0d1117;
            border-radius: 10px;
            padding: 20px;
            overflow-x: auto;
            max-height: 400px;
            overflow-y: auto;
            font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
            font-size: 13px;
            line-height: 1.5;
            color: #c9d1d9;
            border: 1px solid #30363d;
        }
        
        .code-preview code {
            white-space: pre;
        }
        
        /* Scrollbar */
        ::-webkit-scrollbar {
            width: 8px;
        }
        
        ::-webkit-scrollbar-track {
            background: rgba(0,0,0,0.2);
            border-radius: 4px;
        }
        
        ::-webkit-scrollbar-thumb {
            background: var(--border);
            border-radius: 4px;
        }
        
        ::-webkit-scrollbar-thumb:hover {
            background: rgba(255,255,255,0.2);
        }
        
        /* Loading */
        .loading {
            display: inline-block;
            width: 20px;
            height: 20px;
            border: 2px solid rgba(255,255,255,0.3);
            border-radius: 50%;
            border-top-color: white;
            animation: spin 0.8s linear infinite;
        }
        
        @keyframes spin {
            to { transform: rotate(360deg); }
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Blueprint Builder</h1>
            <p class="subtitle">Build apps visually with composable blocks</p>
        </header>
        
        <div class="main-grid">
            <div class="panel">
                <h2>Your Project</h2>
                
                <div class="form-group">
                    <label for="projectName">Project Name</label>
                    <input type="text" id="projectName" placeholder="my-awesome-app" value="my_app">
                </div>
                
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea id="description" placeholder="What does your app do?">A simple web application</textarea>
                </div>
                
                <div class="selected-summary">
                    <h3>Selected Blocks (<span id="blockCount">0</span>)</h3>
                    <div class="selected-tags" id="selectedTags">
                        <span style="color: var(--text-dim); font-size: 0.9em;">Click blocks to add them</span>
                    </div>
                </div>
            </div>
            
            <div class="panel">
                <h2>Available Blocks</h2>
                <div class="blocks-grid" id="blocksGrid">
                    <div style="color: var(--text-dim);">Loading blocks...</div>
                </div>
            </div>
        </div>
        
        <!-- Live Preview Panel -->
        <div class="panel preview-panel" style="margin-top: 30px;">
            <h2>Live Code Preview</h2>
            <pre class="code-preview" id="codePreview"><code>// Select blocks to see generated code...</code></pre>
        </div>
        
        <div class="generate-section">
            <button class="btn-generate" id="generateBtn" onclick="generateApp()">
                Generate App
            </button>
        </div>
        
        <div class="result-panel" id="resultPanel">
            <div class="result-content">
                <h3>App Generated Successfully!</h3>
                <p>Your app has been created at:</p>
                <code id="resultPath"></code>
                <p>To run it:</p>
                <code id="resultCmd"></code>
                <button class="btn-run" onclick="copyCommand()">Copy Command</button>
            </div>
        </div>
    </div>
    
    <script>
        let blocks = [];
        let selectedBlocks = new Set();
        
        // Load blocks on page load
        async function loadBlocks() {
            try {
                const response = await fetch('/api/blocks');
                const data = await response.json();
                blocks = data.blocks;
                renderBlocks();
            } catch (error) {
                console.error('Failed to load blocks:', error);
                document.getElementById('blocksGrid').innerHTML = 
                    '<div style="color: #e74c3c;">Failed to load blocks</div>';
            }
        }
        
        function renderBlocks() {
            const grid = document.getElementById('blocksGrid');
            grid.innerHTML = blocks.map(block => `
                <div class="block-card ${selectedBlocks.has(block.id) ? 'selected' : ''}" 
                     onclick="toggleBlock('${block.id}')">
                    <div class="name">${block.name}</div>
                    <div class="desc">${block.description}</div>
                    <div class="ports">
                        ${block.provides.slice(0, 2).map(p => 
                            `<span class="port-tag provides">${p.name}</span>`
                        ).join('')}
                        ${block.requires.slice(0, 1).map(p => 
                            `<span class="port-tag">${p.name}</span>`
                        ).join('')}
                    </div>
                </div>
            `).join('');
        }
        
        function toggleBlock(blockId) {
            if (selectedBlocks.has(blockId)) {
                selectedBlocks.delete(blockId);
            } else {
                selectedBlocks.add(blockId);
            }
            renderBlocks();
            renderSelectedTags();
            updatePreview();
        }
        
        async function updatePreview() {
            const previewEl = document.getElementById('codePreview');
            
            try {
                const response = await fetch('/api/preview', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        name: document.getElementById('projectName').value,
                        description: document.getElementById('description').value,
                        blocks: Array.from(selectedBlocks)
                    })
                });
                
                const result = await response.json();
                previewEl.innerHTML = `<code>${escapeHtml(result.code)}</code>`;
            } catch (error) {
                console.error('Preview failed:', error);
            }
        }
        
        function escapeHtml(text) {
            const div = document.createElement('div');
            div.textContent = text;
            return div.innerHTML;
        }
        
        function renderSelectedTags() {
            const container = document.getElementById('selectedTags');
            document.getElementById('blockCount').textContent = selectedBlocks.size;
            
            if (selectedBlocks.size === 0) {
                container.innerHTML = '<span style="color: var(--text-dim); font-size: 0.9em;">Click blocks to add them</span>';
                return;
            }
            
            container.innerHTML = Array.from(selectedBlocks).map(id => {
                const block = blocks.find(b => b.id === id);
                return `
                    <span class="selected-tag">
                        ${block ? block.name : id}
                        <span class="remove" onclick="event.stopPropagation(); toggleBlock('${id}')">x</span>
                    </span>
                `;
            }).join('');
        }
        
        async function generateApp() {
            const btn = document.getElementById('generateBtn');
            const originalText = btn.innerHTML;
            btn.innerHTML = '<span class="loading"></span> Generating...';
            btn.disabled = true;
            
            try {
                const response = await fetch('/api/generate', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        name: document.getElementById('projectName').value,
                        description: document.getElementById('description').value,
                        blocks: Array.from(selectedBlocks)
                    })
                });
                
                const result = await response.json();
                
                if (result.success) {
                    document.getElementById('resultPath').textContent = result.path;
                    document.getElementById('resultCmd').textContent = result.run_command;
                    document.getElementById('resultPanel').classList.add('show');
                }
            } catch (error) {
                console.error('Generation failed:', error);
                alert('Failed to generate app. Check console for details.');
            } finally {
                btn.innerHTML = originalText;
                btn.disabled = false;
            }
        }
        
        function copyCommand() {
            const cmd = document.getElementById('resultCmd').textContent;
            navigator.clipboard.writeText(cmd).then(() => {
                const btn = event.target;
                btn.textContent = 'Copied!';
                setTimeout(() => btn.textContent = 'Copy Command', 2000);
            });
        }
        
        // Initialize
        loadBlocks();
        updatePreview();
        
        // Update preview when inputs change
        document.getElementById('projectName').addEventListener('input', debounce(updatePreview, 300));
        document.getElementById('description').addEventListener('input', debounce(updatePreview, 300));
        
        function debounce(func, wait) {
            let timeout;
            return function(...args) {
                clearTimeout(timeout);
                timeout = setTimeout(() => func.apply(this, args), wait);
            };
        }
    </script>
</body>
</html>'''


def main():
    """Start the visual builder server."""
    OUTPUT_DIR.mkdir(exist_ok=True)
    
    print("=" * 50)
    print("  Blueprint Visual Builder")
    print("=" * 50)
    print(f"  Server: http://localhost:{PORT}")
    print(f"  Output: {OUTPUT_DIR}")
    print("=" * 50)
    print("  Press Ctrl+C to stop")
    print()
    
    # Open browser after a short delay
    def open_browser():
        import time
        time.sleep(1)
        webbrowser.open(f"http://localhost:{PORT}")
    
    threading.Thread(target=open_browser, daemon=True).start()
    
    # Start server
    server = HTTPServer(("", PORT), BuilderHandler)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down...")
        server.shutdown()


if __name__ == "__main__":
    main()
